

import { useEffect, useState } from "react";
import axios from "axios";
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  ResponsiveContainer,
  Legend,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  LineChart,
  Line,
} from "recharts";

function Charts() {
  const [planData, setPlanData] = useState([]);
  const [priceData, setPriceData] = useState([]);
  const [revenueData, setRevenueData] = useState([]);

  useEffect(() => {
    const fetchPlans = async () => {
      try {
        const res = await axios.get(
          `${import.meta.env.VITE_API_URL}/plans`
        );

        let basic = 0;
        let standard = 0;
        let premium = 0;

        const prices = {
          basic: 199,
          standard: 499,
          premium: 649,
        };

        res.data.forEach((item) => {
          const plan = item.plan.toLowerCase();

          if (plan === "basic") basic++;
          else if (plan === "standard") standard++;
          else if (plan === "premium") premium++;
        });

       
        setPlanData([
          { name: "Basic", value: basic },
          { name: "Standard", value: standard },
          { name: "Premium", value: premium },
        ]);

        setPriceData([
  {
    name: "Basic",
    price: basic > 0 ? prices.basic : 199,
    subscribers: basic,
  },
  {
    name: "Standard",
    price: standard > 0 ? prices.standard : 499,
    subscribers: standard,
  },
  {
    name: "Premium",
    price: premium > 0 ? prices.premium : 799, 
    subscribers: premium,
  },
]);

       
        setRevenueData([
          {
            name: "Basic",
            revenue: basic * prices.basic,
          },
          {
            name: "Standard",
            revenue: standard * prices.standard,
          },
          {
            name: "Premium",
            revenue: premium * prices.premium,
          },
        ]);
      } catch (error) {
        console.error("Error fetching plans", error);
      }
    };

    fetchPlans();
  }, []);

  const COLORS = ["#E50914", "#0071EB", "#FFA500"];

  return (
    <div className="dashboard-charts">
      
      <div className="chart-box">
        <h2 className="head">Plan Distribution</h2>
        <ResponsiveContainer width="100%" height="90%">
          <PieChart>
            <Pie
              data={planData}
              dataKey="value"
              cx="50%"
              cy="50%"
              outerRadius={100}
              label={({ percent }) =>
                `${(percent * 100).toFixed(0)}%`
              }
            >
              {planData.map((entry, index) => (
                <Cell
                  key={index}
                  fill={COLORS[index % COLORS.length]}
                />
              ))}
            </Pie>
            <Tooltip />
            <Legend />
          </PieChart>
        </ResponsiveContainer>
      </div>

      <div className="chart-box">
        <h2 className="head">Plan Price vs Subscribers</h2>
        <ResponsiveContainer width="100%" height="90%">
          <BarChart data={priceData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="name" />
            <YAxis />
            <Tooltip />
            <Legend />
            <Bar
              dataKey="price"
              fill="#0071EB"
              name="Price (₹)"
            />
            <Bar
              dataKey="subscribers"
              fill="#00C853"
              name="Subscribers"
            />
          </BarChart>
        </ResponsiveContainer>
      </div>

    
      <div className="chart-box">
        <h2 className="head">Revenue Generated by Plans</h2>
        <ResponsiveContainer width="100%" height="90%">
          <LineChart data={revenueData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="name" />
            <YAxis />
            <Tooltip />
            <Legend />
            <Line
              type="monotone"
              dataKey="revenue"
              stroke="#E50914"
              strokeWidth={3}
              name="Revenue (₹)"
            />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

export default Charts;